
version: '3'
services:
 radarr:
  container_name: Radarr
  restart: unless-stopped
  ports:
   - 7878:7878
  volumes:
    - /Containers/Radarr/config:/config
    - /Share/movies:/movies
    - /Containers/Sonarr/downloads:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Australia/Sydney
  image: linuxserver/radarr
 
 sonarr:
  container_name: Sonarr
  restart: unless-stopped
  ports:
   - 8989:8989
  volumes:
    - /Containers/Sonarr/config:/config
    - /Share/tv:/tv
    - /Containers/Sonarr/downloads:/downloads
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Australia/Sydney
  image: linuxserver/sonarr
 
 # Fix up! Prts & env
 prowlarr:
  container_name: Prowlarr
  restart: unless-stopped
  ports:
   - x:x
  volumes:
   - /Containers/Prowlarr/config:/config
  environment:
   - #something
  image: linuxserver/prowlarr


 # Fix up! Prts & env
 deluge:
  container_name: Deluge
  restart: unless-stopped
  ports:
   - x:x
  volumes:
   - /Containers/Deluge/config:/config
   - /Containers/Sonarr/downloads:/downloads
  environment:
   - #something
  image: TBC

# Fix up! #Prts & env w/ image
 overseerr:
  container_name: Overseerr
  restart: unless-stopped
  ports:
   - x:x
  volumes:
   - /Containers/Overseerr/config:/config
  environment:
   - #something
  image: #something


